name: er_test

on:
  push:
    paths-ignore:
      - '**.md'
    
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ryuichiueda/emcl.git
         cd emcl/test/docker
         sed -i "s;clone;clone -b ${GITHUB_REF#refs/heads/};" Dockerfile
         docker build -t test .
      - name: Reset test on Gazebo
        run: |
         docker run test /bin/bash -c 'source ~/.bashrc && xvfb-run --auto-servernum -s "-screen 0 1400x900x24" /catkin_ws/src/emcl/test/er_test.bash'
