name: vi_test

on:
  push:
    paths-ignore:
      - '**.md'
    
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
         git clone -b "${GITHUB_REF#refs/heads/}" https://github.com/ryuichiueda/emcl.git
         cd emcl/docker
         docker build -t test .
      - name: Reset test on Gazebo
        run: |
         docker run -it test /bin/bash -c 'source ~/.bashrc && /catkin_ws/src/emcl/test/er_test.bash'
